version: "3.8"
services:
  orders:
    container_name: orders
    build:
      context: .
      dockerfile: orders/Dockerfile
    depends_on:
      mongodb:
        condition: service_started
      stock:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - STOCK_GRPC_TARGET=stock:2001
      # - RABBIT_URI=amqp://guest:guest@rabbitmq/
    ports:
      - "2000:2000"

  stock:
    container_name: stock
    build:
      context: .
      dockerfile: stock/Dockerfile
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - microservices-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      # - RABBIT_URI=amqp://guest:guest@rabbitmq/
    ports:
      - "2001:2001"

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    depends_on:
      orders:
        condition: service_started
    networks:
      - microservices-network
    environment:
      - ORDERS_GRPC_TARGET=orders:2000
    ports:
      - "8000:8000"

  payment:
    container_name: payment
    build:
      context: .
      dockerfile: payment/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      orders:
        condition: service_started
    networks:
      - microservices-network
    environment:
      - ORDERS_GRPC_TARGET=orders:2000
      # - RABBIT_URI=amqp://guest:guest@rabbitmq/
      # - PAYMENT_PORT=3000
    ports:
      - "8001:8001"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    networks:
      - microservices-network

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - microservices-network
    volumes:
      - mongo-data:/data/db

networks:
  microservices-network:
    driver: bridge

volumes:
  mongo-data: